services:
  postgres:
    image: postgres:16
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: vaibhaw
      POSTGRES_PASSWORD: vaibhaw
      POSTGRES_DB: moneywise
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vaibhaw -d moneywise"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
